### ISSUE TITLE
`getInitializationEntries` contents causes incorrect `Error` position

### ISSUE THREAD

**Issue by oblador** [callstack/repack#128]
## Environment

Both iOS and Android, with or without hermes.

## Description

When throwing an error inside a repack app (including the TesterApp) the line + column combination is not matching the actual position in the bundle file, therefore the source map lookup ends up on the wrong file/line. The produced source map itself is correct and maps perfectly if getting the position by inspecting the bundle manually or running the bundle via node. 

This seems to be caused by the import of `react-native` package somehow. 

## Reproducible Demo

Edit `TesterApp/index.js` to be:
```
throw new Error('Lol');
```

and remove `ReactNative.getInitializationEntries` spread from `webpack.config.js` and observe that the line+column thrown in RN are correct. Add back `ReactNative.getInitializationEntries` and see that it doesn't match anymore.

**Comment by TMaszko** [comment]
Hi, after throughout investigation we know that:
without any changes to the webpack config we've got following results:
- dev=true,minify=false ->  correct stack trace
- dev=true,minify=true -> incorrect stack trace
- dev=false, minify=true -> incorrect stack trace

with your changes:
- dev=true, minify=false -> correct stack trace
- dev=true, minify=true -> correct stack trace (/*webpackChunkNamec*/) will be removed as well so just keep that in mind and be careful.
- dev=false, minify=true -> correct stack trace

Turned out that comments that start with `@license` and `!` like those generated by the `webpack` :) caused JSC to return wrong column number when Error was thrown. In the dev mode before our `index` there is a different type of comment and probably that's the reason why it works properly. Surprisingly on Hermes everything should work as suppose to !
