### ISSUE TITLE
Repack v3 HMR breaks React Native inspector/devtools

### ISSUE THREAD

**Issue by bea73693** [callstack/repack#251]
## Environment

`"@callstack/repack": "^3.0.0"`
`"react-native": "0.70.1"`
node: v16.14.2
yarn: 1.22.19

## Description

App throws error when attempting to access react native inspector (cmd+d) -> 'Show Inspector' and no inspection tools are available. After doing this the menu shows 'Hide Inspector' option and clicking this shows the same error. 

Error in console:
`[Console] Invariant Violation: Expected to find at least one React Native renderer on DevTools hook., js engine: hermes`

Error on device: 
<img width="390" alt="Screen Shot 2022-09-27 at 12 14 38 PM" src="https://user-images.githubusercontent.com/56211155/192592669-d2e15811-64e8-4e56-baa2-5d37e5f188ee.png">

Disabling HMR in webpack.config.js shows the inspector as expected. 

## Reproducible Demo

1. Init a new react native project, for example:
`npx react-native init test_app --template react-native-template-typescript`
2. Configure Repack according to https://re-pack.netlify.app/docs/getting-started#dependencies, using updated webpack config template under v3: https://github.com/callstack/repack/blob/v3/templates/webpack.config.cjs. 
3. Run repack, `react-native webpack-start` and run `yarn ios --no-packager`
4. Open simulator menu (cmd+d) and click 'Show Inspector', error shown and no inspector tools available. 
5. Restart repack with lines 47-49 uncommented (sets HMR to false), open menu and inspector works as expected.

**Comment by jinliming2** [comment]
Seems like this issue was related to `@pmmmwh/react-refresh-webpack-plugin` v0.5.

I found two solutions:
1. lock `@pmmmwh/react-refresh-webpack-plugin` to `0.4.3` by adding `resolutions` to package.json:
   ```json
   "resolutions": {
       "@pmmmwh/react-refresh-webpack-plugin": "^0.4.3"
   }
   ```
2. Modify `node_modules/react-devtools-core/dist/backend.js`, search `installHook` function and remove `target.hasOwnProperty` check (first three lines.)
   ```diff
    function installHook(target) {
   -    if (target.hasOwnProperty('__REACT_DEVTOOLS_GLOBAL_HOOK__')) {
   -        return null;
   -    }

        var targetConsole = console;
        var targetConsoleMethods = {};
   ```

**Comment by arelian11** [comment]
In my tests, downgrading to 0.4.3 made the initial webpack builds much slower - so that wasn't an option, unfortunately.
Removing the `target.hasOwnProperty()` check from `backend.js` also didn't work - that allowed connecting to dev tools but broke HMR.

I think this has something to do with the patch made in https://github.com/callstack/repack/pull/1 to initialize devtools before react-refresh. It seems to no longer work with the latest version of `@pmmmwh/react-refresh-webpack-plugin`.

My solution: 

In https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/0610d3c11ee54733612eb1a8a12400cf42ed24c7/lib/index.js#L75, use the legacy logic for injecting the plugin:

```
-   if (EntryPlugin) {
+   if (false) {
      // Prepended entries does not care about injection order,
      // so we can utilise EntryPlugin for simpler logic.
      addEntries.prependEntries.forEach((entry) => {
        new EntryPlugin(compiler.context, entry, { name: undefined }).apply(compiler);
      });
```

There is probably a much cleaner way to do this, but I thought this would help point people down the right track to a real solution.

**Comment by sleeper-luke** [comment]
In my tests, downgrading to 0.4.3 made the initial webpack builds much slower - so that wasn't an option, unfortunately.

Removing the `target.hasOwnProperty()` check from `backend.js` also didn't work - that allowed connecting to dev tools but broke HMR.

I think this has something to do with the patch made in https://github.com/callstack/repack/pull/1 to initialize devtools before react-refresh. (Specifically this block [here](https://github.com/callstack/repack/blob/ff0451651fe0feec3669da7e4aeda46ccbbbdc5f/src/webpack/plugins/DevServerPlugin/DevServerPlugin.ts#L84)) It seems to no longer work with the latest version of `@pmmmwh/react-refresh-webpack-plugin`.

My solution: 

In https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/0610d3c11ee54733612eb1a8a12400cf42ed24c7/lib/index.js#L75, use the legacy logic for injecting the plugin:

```
-   if (EntryPlugin) {
+   if (false) {
      // Prepended entries does not care about injection order,
      // so we can utilise EntryPlugin for simpler logic.
      addEntries.prependEntries.forEach((entry) => {
        new EntryPlugin(compiler.context, entry, { name: undefined }).apply(compiler);
      });
```

By doing this, the patch to re-arrange the plugin initialization order is able to correctly find the refresh plugin, because it hits this block instead:

```
    } else {
      compiler.options.entry = injectRefreshEntry(compiler.options.entry, addEntries);
    }
```

There is probably a more correct way to do this (maybe change the patch to correctly find the react-refresh plugin in the new `EntryPlugin` flow?), but I thought this would help point people down the right track.

**Comment by suhassasuke** [comment]
> Seems like this issue was related to `@pmmmwh/react-refresh-webpack-plugin` v0.5.
> 
> I found two solutions:
> 
> 1. lock `@pmmmwh/react-refresh-webpack-plugin` to `0.4.3` by adding `resolutions` to package.json:
>    ```json
>    "resolutions": {
>        "@pmmmwh/react-refresh-webpack-plugin": "^0.4.3"
>    }
>    ```
> 2. Modify `node_modules/react-devtools-core/dist/backend.js`, search `installHook` function and remove `target.hasOwnProperty` check (first three lines.) And use [patch-package](https://www.npmjs.com/package/patch-package) to persistent changes.
>    ```diff
>     function installHook(target) {
>    -    if (target.hasOwnProperty('__REACT_DEVTOOLS_GLOBAL_HOOK__')) {
>    -        return null;
>    -    }
>    
>         var targetConsole = console;
>         var targetConsoleMethods = {};
>    ```

also check if all the .lock file has same version of ["@pmmmwh/react-refresh-webpack-plugin": "^0.4.3"]. Remove other version of react-refresh-webpack-plugin in .lock files. [in All Mini App also]
