### ISSUE TITLE
Does this comply with Apple's guideline 2.5.2?

### ISSUE THREAD

**Issue by idrakimuhamad** [callstack/repack#284]
With the code splitting, I'm able to send an updated bundle of a portion of my app without re-submitting binary, and without using CodePush. This is great, I think.

However, I'm wondering if any of you guys used this in production and whether or not you have any issue with your app submission and review, especially on the guideline for 2.5.2?

> 2.5.2 Apps should be self-contained in their bundles, and may not read or write data outside the designated container area, nor may they download, install, or execute code which introduces or changes features or functionality of the app, including other apps. Educational apps designed to teach, develop, or allow students to test executable code may, in limited circumstances, download code provided that such code is not used for other purposes. Such apps must make the source code provided by the Application completely viewable and editable by the user.

https://developer.apple.com/app-store/review/guidelines/#2.5.2

I assumed so long as your bundle update doesn't alter too much of the feature look and functionality it shouldn't be an issue, but still hope to hear some experts from anyone who have used this in production.

Thanks!

**Comment by RafikiTiki** [comment]
Your question is definitely a valid one, thanks for asking that!

Similar to publishing updates via CodePush – final app reviewer decision might depend on lot of factors. General rule of thumb is to be as transparent in the review process as possible. For example if in your app any given feature is available only for a specific group of users, you'll need to provide credentials to these kind of accounts to the Reviewer, and precise instructions on how to access these features, so that they can evaluate each an every on-demand feature during their review process.

Point 4.7 in the guidelines gives us some flexibility in terms of downloadable content: https://developer.apple.com/app-store/review/guidelines/#4.7

In the Re.Pack documentation there's a page dedicated to this topic: https://re-pack.netlify.app/docs/code-splitting/concept
