### ISSUE TITLE
Build release version iOS / android with Federation module

### ISSUE THREAD

**Issue by PeaGo** [callstack/repack#286]
How to build app with Federation module in release version (ipa, apk) ?
I seperate app into 2 or more miniapps, how to build all into one apk or ipa file ?

**Comment by rakshith** [comment]
Just adding one more info here in order to correct the context, after bundling with webpack-bundle for release, how can i provide my own custom URL like below, please let me know the syntax to get jsBundles from our own server, assume the server simple gives response as jsBundls when its called

const resolveURL = Federated.createURLResolver({
  containers: {
    rnminiappone: 'http://my-own-server/build/output/android/[name][ext]',
    rnminiapptwo: 'http://my-own-server/build/output/ios/[name][ext]',
  },
});

**Comment by nhatvuminh** [comment]
I'm interested ///

**Comment by ViniciusUrias** [comment]
I need to assembleRelease my two child apps and then I should assembleRelease the host app? Do I have to make any path config for the host bundle take the others two release apks?

**Comment by RafikiTiki** [comment]
That depends on what you want to achieve. @ViniciusUrias Please open a new issue with a diagram and a description of the architecture you want to achieve and possibly a repository with some configuration already in it.

Since there's no response from @PeaGo I'm closing this issue, but please feel free to comment here if you need any more help.
