### ISSUE TITLE
Repack(or webpack) produces invalid JS bundle?

### ISSUE THREAD

**Issue by NepeinAV** [callstack/repack#301]
## Ask your Question

Hi all!

I'm trying to replace metro with repack in a fresh React native 0.70 app and without additional dependencies everything works perfect. But after adding the library `camelcase-keys` to the app, I started getting following runtime errors:

<img src="https://user-images.githubusercontent.com/33036510/216362359-6d289bb7-3f58-49cf-8767-d2a46446bc07.png" width="300" />

In JS bundle from local dev server (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.repack&modulesOnly=false&runModule=true) we see, that module `./node_modules/camelcase-keys/index.js` uses plain `require` function, instead of `__webpack_require__ `, which does not exists in Hermes runtime and throwing error. What do you think is going on here? Is this some misconfiguration in my app or Repack issue?

## Reproduction

Repo: https://github.com/NepeinAV/repack_repro

Steps:
- Generate fresh RN 0.70.6 app
- Follow Repack installation guide
- Install `camelcase-keys` lib
- Import it in App.js file
- Run app
- Get the error

**Comment by jbroma** [comment]
Hi @NepeinAV

I've investigated the issue and this problem occurs because `camelcase-keys` is a pure ESM library, therefore we need to handle it a little bit different. We need to add a separate rule in our `webpack.config.mjs` to handle ESM libraries as shown below:

```diff
diff --git a/webpack.config.mjs b/webpack.config.mjs
index 467d188..d55aa84 100644
--- a/webpack.config.mjs
+++ b/webpack.config.mjs
@@ -165,6 +165,24 @@ export default (env) => {
             options: {},
           },
         },
+        {
+          test: /\.[jt]sx?$/,
+          include: [
+            /node_modules(.*[/\\])+camelcase-keys/,
+            /node_modules(.*[/\\])+quick-lru/,
+          ],
+          use: {
+            loader: 'babel-loader',
+            options: {
+              presets: [
+                [
+                  'module:metro-react-native-babel-preset',
+                  {disableImportExportTransform: true},
+                ],
+              ],
+            },
+          },
+        },
         /**
          * Here you can adjust loader that will process your files.
          *
```

Besides adding `camelcase-keys`, we also needed to add `quick-lru` as it's a dependency of `camelcase-keys` and is also a pure ESM library.

If you would like to know more, you can check out this answer to a similar issue: https://github.com/callstack/repack/issues/359#issuecomment-1559509051
