### ISSUE TITLE
Any limitation to use Re.Pack with Expo SDK 47 (and greater)?

### ISSUE THREAD

**Issue by jfbaro** [callstack/repack#304]

**Comment by jfbaro** [comment]
Please. Any tip would be appreciated. Now that we have Expo Dev Client is this still a limitation?

**Comment by thymikee** [comment]
Hey @jfbaro! I don't have immediate answer on that, but I'll put this on our research plan to see if we can have e.g. a mini-app in Module Federation approach developed with Expo client. It's gonna be way trickier if we'd want to use Expo for a host because we build on Webpack.

**Comment by iambharath87** [comment]
@thymikee an example app with expo would be very much welcome. I created an issue earlier with a [sample repo](https://github.com/iambharath87/expo-repack-starter) i was trying. Maybe its helpful.

**Comment by outsung** [comment]
I've created an example app that includes Expo. You can find the repository [here](https://github.com/outsung/expo-repack-monorepo).

I followed the structure provided in the [callstack/repack-examples (module-federation)](https://github.com/callstack/repack-examples/tree/main/module-federation) repository.

#### Modifications Made:

1. **Added a Plugin to Modify IOS Native Code:**

   I added a [plugin](https://github.com/outsung/expo-repack-monorepo/blob/main/apps/host/plugin/withRepack.js) to modify the iOS native code. (Note: Android implementation is pending.)

2. **Used `metro-react-native-babel-preset`:**

   Instead of `babel-preset-expo`, I switched to using `metro-react-native-babel-preset` in the [babel.config.js](https://github.com/outsung/expo-repack-monorepo/blob/main/apps/host/babel.config.js). Ensure you install the same version of `metro-react-native-babel-preset` as specified in `babel-preset-expo`. Multiple versions can cause errors.

3. **Fix for Expo in `webpack.config.mjs`:**

   I replaced `@expo` with `expo` in the [webpack.config.mjs](https://github.com/outsung/expo-repack-monorepo/blob/082633edded401b7f599ecebd8e033d47266b8fd/apps/host/webpack.config.mjs#L157).

Feel free to review the repository for more details.

**Comment by msgtobala** [comment]
@outsung, As a beginner I am not able to understand how to run your repository [expo-repack-monorepo](https://github.com/outsung/expo-repack-monorepo). Please help me on running the repository

**Comment by outsung** [comment]
@msgtobala My answer is late, but are you saying you don't know which part?
