### ISSUE TITLE
Get URL of a script stored on filesystem on the target mobile device

### ISSUE THREAD

**Issue by rakshith** [callstack/repack#313]
## Provide URL of the mobile filesystem to refer built bundles located in assets folder or any other?

Please provide the URL path required to pass in order to access the chunks/container located in asset folder(android) of the mobile system, if iOS also please provide

For reference code below issues:
let url;
  if (caller === 'main') {
    url = Script.getDevServerURL(scriptId);
  } else {
    url = Script.getFileSystemURL(`asset/${scriptId}`);
  }

**Comment by RafikiTiki** [comment]
Hello, please refer to the repack documentation on `local chunks`. It can be found here: https://re-pack.netlify.app/docs/code-splitting/local-vs-remote-chunks#local-chunks

If you want to look at the implementation in the minimal project setup – refer to the [TesterApp](https://github.com/callstack/repack/tree/main/packages/TesterApp). In summary you'll need to:
1. Think of a naming convention for the local chunks, and rename all of the files you'd like to be local chunks. In TesterApp it's `<Component_Name>.local.tsx`
2. Configure `RepackPlugin` in `webpack.config` to produce local chunks: https://github.com/callstack/repack/blob/main/packages/TesterApp/webpack.config.mjs#L235-L245
3. Refactor `ScriptManager` resolver so that it knows how to handle local chunks: https://github.com/callstack/repack/blob/main/packages/TesterApp/index.js#L16-L21
