### ISSUE TITLE
Native dependency/Bridges integration

### ISSUE THREAD

**Issue by BologaMarius** [callstack/repack#321]
## Ask your Question

I been going through the documentation and I found little to none documentation about integration of native components using repack when it comes to module federation.

What is mentioned in the documentation is that "Host application must have native modules used in other containers" and it's given as an example react-native-reanimated which seems pretty straight forward. What happens if there are different versions of the same module?

Now the questions that I have, let say I have my own native SDK and I write a react native wrapper for it. Can that live in the app module(remote)? Or all the handling needs to happen in the host app?

**Comment by BologaMarius** [comment]
Thank you for explanation, I think it makes sense now. I assume for example if I create a package for my native module and react native bindings, I can add it to both my host app and the standalone app and benefit of the module federation.

Another question related to the version that is shared between the federated modules. I see in the documentation given as example react native reanimated. Is the same version (the one from the host app) shared with all the other standalone apps? Can these versions be different?  Is there a single instance as is needed `react` and `react-native dependency`? What's the relationship between version? I tried for example with @react-native-async-storage/async-storage, having one version(1.18.0) in host and having one version(1.16.1) in the standalone app did not seem to affect the overall build/app even though I passed `requireVersion` and set it up to 1.18.0

**Comment by RafikiTiki** [comment]
> I assume for example if I create a package for my native module and react native bindings, I can add it to both my host app and the standalone app and benefit of the module federation.

That's correct. One thing to keep in mind is that in case you use a new dependency (with Native Code) in the part of the Other Standalone App that your Host App is consuming (Federated Module) – you'll need to add that dependency to the Host App as well, otherwise it won't work since Native Code can't be _shared_ by the Webpack.

Answering the versioning questions: As a general rule of thumb you should always keep the dependencies across all of the apps written in Module Federation architecture in sync. Otherwise, sooner or later, all sorts of problems will appear. In case of `@react-native-async-storage/async-storage` – there probably weren't any significant changes in the API and Native Code of that library which would case problems but it's not always the case. You should have received a warning in the console about missmatch between the required version and the actual version of this library provided by the Host App.

As for the single instance requirement (a `singleton` flag in the `shared` configuration in webpack.config) – it's needed in a few scenarios:
- if a library registers a Native View – the app will crash if a second View with the same name is registered
- if a library is relying on React.Context – if you don't specify it's a singleton then you'll end up with two instances of this library (one in the Host App, and a second one in the Federated Module) which will result in two instances of React.Context with no way of communicating with each other. Depending on your use case it might be good or bad.
