### ISSUE TITLE
How to properly bundle Federated Module Container for CDN?

### ISSUE THREAD

**Issue by sschottler** [callstack/repack#324]
Two questions:

1. Is this the right way to generate JS files for a federated module container to deploy to CDN?

`STANDALONE=0 react-native webpack-bundle --entry-file=./src/index.ts --dev=false --platform='ios'`

2. When I run that command, the `[federatedmodulename].container.bundle` file was much bigger than I expected. Seemed like it included `react` and `react-native`. Is this expected with below webpack config? Do I need to use the [externals](https://webpack.js.org/configuration/externals/) config to exclude them? My understanding of shared config is that it prevents two instances of react at runtime (at least with the local webpack dev server) so the context tree doesn't get messed up. I thought that config would also prevent react from being included in a production bundle as well (especially since `STANDALONE` flag is false), but I might be misunderstanding something.

```js
shared: {
  // peerDependencies:
  react: {
    ...Repack.Federated.SHARED_REACT,
    eager: STANDALONE, 
  },
  "react-native": {
    ...Repack.Federated.SHARED_REACT_NATIVE,
    eager: STANDALONE, 
    requiredVersion: "0.68.5",
  },
```

**Comment by RafikiTiki** [comment]
1. Provided you have `STANDALONE` flag parsing implemented in this way:
```
const STANDALONE = Boolean(process.env.STANDALONE);
```
the script you shared is the correct way to generate bundles that can then be uploaded to a CDN and consumed by Host Apps. I personally like to skip `STANDALONE` flag in the production build script since it'll fall back to undefined -> false in the webpack.config if it's not provided.

2. What did you expect the container.bundle file to be made of? Why does it seem like the `react` and `react-native` code is bundled into the `[federatedmodulename].container.bundle`? I'm asking because maybe in the future, we are going to prepare a docs page about diving a little deeper into the structure of the bundles themselves, and understanding what is not clear for the Repack users will help us greatly. 

Try re-runing the build with STANDALONE flag set to 1, or just hardcode `true` int o the `eager` filed in shared dependencies, like you would do to generate Host App bundles – you should be able to see the `react` and `react-native` modules _inlined_ into the container bundle then

**Comment by sschottler** [comment]
Ah, your comment helped me figure out what was happening. Setting `STANDALONE=0` explicitly in my script caused this to be truthy in `webpack.config.mjs`:

```js
const STANDALONE = Boolean(process.env.STANDALONE);
```

I needed to not set it so it is `undefined` and `falsy` and `eager` gets correctly set to `false` later in the module federation config plugin for `react` and `react-native`. I no longer see `react` and `react-native` in the bundle. Goes from 757kb to 8kb and loads from some webpack sharing react path instead of inlining. That is what I expected to see. Thanks for your help! Might help to add a script similar to this to the repack-examples app1/app2:

```
    "build-cdn-ios": "react-native webpack-bundle --entry-file=index.js --dev=false --platform='ios'"
```

**Comment by DivyatejaChe** [comment]
@sschottler  @RafikiTiki Hi both, I attempted to bundle my miniapps and intended to serve them from CDN. Bundling generated [name].container.bundle and I uploaded it on jsdelivr CDN.

When I try to load it into my host app, it doesn't load and keeps loading. Please help solve this. I raised a question for the same (check [here](https://github.com/callstack/super-app-showcase/issues/80))

[github repo](https://github.com/DivyatejaChe/pnpm-monorepo-repack) and [CDN URL](https://cdn.jsdelivr.net/gh/DivyatejaChe/df-repack@1629c48afc875fe2afb72e251f5d24c6b9cd6c66/auth.container.bundle.js) are attached for your reference
