### ISSUE TITLE
Does repack works fine on Windows?

### ISSUE THREAD

**Issue by ViniciusUrias** [callstack/repack#340]
### Discussed in https://github.com/callstack/repack/discussions/339

<div type='discussions-op-text'>

<sup>Originally posted by **ViniciusUrias** April 11, 2023</sup>
I was using windows 10, but all repack/module-federation examples were crashing.
Errors like:
'Can't find __webpack_require__';
'[ERR_UNSUPPORTED_ESM_URL_SCHEME]';
'Unhandled error. ([ScriptManager] Failed to load script:)';

Then I upgraded to windows 11 and the same errors still ocurring.
I think the last solution is change to some linux distro.
Obs: I tested it like 100 times before coming here, used 3 different versions of node, react and react-native, tested with .mjs, .cjs and .js, created a brand new app to configure, cloned the existing examples and I simply can't find a solution</div>

**Comment by piccinnigius** [comment]
Hi, I was able to make it work with Windows 11. 
What can i say is that:

1.  `webpack_require` or cant't find xxx method can be fixed commonly by adding `/node_modules(.*[/\\])+@callstack/` or correspective dependency to babel-loader section in `webpack.config.mjs`.
2. [ERR_UNSUPPORTED_ESM_URL_SCHEME] can be hard-fixed by editing the source code of the @callstack library. This error happens because on windows seems that the require function (on webpack mjs config file) error is fatal and can't be managed by a try catch block and then it raise this error. I'm working on a pull request that can manage this behavior.

hope that this can helps you

**Comment by Ibnunds** [comment]
For windows user need to use webpack-config.cjs template, dont use the .mjs template

**Comment by jbroma** [comment]
Hey @ViniciusUrias,

we've recently released [Re.Pack 3.5.0](https://github.com/callstack/repack/releases/tag/%40callstack%2Frepack%403.5.0) which address a major issue for users on Windows. Try updating `@callstack/repack` to the newest version and see whether your issue is still relevant, thanks!

**Comment by jbroma** [comment]
Closing as issue became stale and solution was provided.

**Comment by LilMaiaV2** [comment]
@callstack/repack not work on windows in react native project
