### ISSUE TITLE
How to invalidate Cache when using ScriptManager.shared.addResolver

### ISSUE THREAD

**Issue by chakravarthi-bb** [callstack/repack#354]
When you host your Bundles in CDN, and want to update a Bundle and let the users download this new updated bundle, is there a way to invalidate cache or download updated bundle

**Comment by RafikiTiki** [comment]
The easiest (and recommended) way to do that would be to put a version of the Bundle in the URL from where it's fetched. By doing so, Repack can figure out that it needs to fetch the new Bundles because the cache key (essentially – the URL) was changed. You can also provide your own implementation to have more granular control over when to download a new bundle – by providing `shouldUpdateScript` function to the resolver configuration.

Here's the implementation of the caching mechanism: https://github.com/callstack/repack/blob/main/packages/repack/src/modules/ScriptManager/ScriptManager.ts#L275-L306

You can also manually invalidate the cache and remove the associated scripts (Bundles) from the filesystem using this method: https://re-pack.netlify.app/docs/api/repack/client/classes/ScriptManager#invalidatescripts
