### ISSUE TITLE
Error bundle when try use react-i18next in host app

### ISSUE THREAD

**Issue by codelessthanyesterday** [callstack/repack#358]
## Environment

Environment :
"react-native": "0.70.6",
"react": "18.1.0",
"webpack": "^5.83.1",
"@callstack/repack": "^3.2.0",

## Description

<img width="362" alt="image" src="https://github.com/callstack/repack/assets/109354280/3c33697f-7166-4a35-987c-92753ed7c2e1">

**Comment by RafikiTiki** [comment]
Please provide a reproduction repo :)

**Comment by ducsotatek** [comment]
Hi @RafikiTiki , Thank you for the response. I just tried it with a very simple app, and everything is fine after I added the react-i18next library. A similar error occurred when I tried it with Yup as well
This is the repo:
https://github.com/ducsotatek/host

**Comment by RafikiTiki** [comment]
@ducsotatek I found a solution to your problem – the first regexp in the babel-loader `include` configuration in webpack.config is too broad – it matches every package whose name starts with `react` and in effect it unnecessarily transpiles `react-i18next`. After tweaking the regexp I was able to successfully build and run the app from your reproduction repo. I'm going to open a PR with this fix soon, but for now please modify your webpack.config file so that it looks like so:

```diff
include: [
-            /node_modules(.*[/\\])+react/,
+            /node_modules(.*[/\\])+react\//,
+            /node_modules(.*[/\\])+react-native\//,
```

**Comment by codelessthanyesterday** [comment]
Thank you for assisting me so quickly. I greatly appreciate that. Everything is fine now.

**Comment by RafikiTiki** [comment]
@codelessthanyesterday There is one small mistake in the diff I sent above, please use the following one. The only change is the regexp for `react-native` packages is not constrained to only `react-native` but will also match any other package prefixed with `react-native` i.e. `react-native-svg`.

```diff
include: [
-            /node_modules(.*[/\\])+react/,
+            /node_modules(.*[/\\])+react\//,
+            /node_modules(.*[/\\])+react-native/,
```
