### ISSUE TITLE
It is possible to fetch a new bundle without reopen the app ? 

### ISSUE THREAD

**Issue by vschan-digiX** [callstack/repack#367]
i want to replace the old bundle and fetch the latest bundle (if there is any) without reopening app is this possible?

**Comment by RafikiTiki** [comment]
By without reopening the app you mean:
1. The user opens the app, and fetches version x.y.z of the mini app -> They close the app -> new version of the mini app is released and it's automatically fetched _in the background_ and is already available for the user at the time they open the app once again, or
2. The user opens the app, and fetches version x.y.z of the mini app -> They keep using the app for a period of time, and during that time, a new version of the app is released -> the app decides it needs to fetch the latest version -> bundle is fetched.

The first approach is out of the scope, at least for now, of Repack. Even if would be implemented in the future, it would not work consistently for all of the users – both Android and iOS are very strict about what can be done in the background. Additionally, the users themselves can disable background activities (refresh) for chosen apps.

The second approach is definitely possible but is not "provided" by the Repack out-of-the-box. There are many:
- architectural concerns: i.e. how should the app get the info that the new version of the mini app got published? Should it poll a server to keep track of the mini app -> latest version dictionary? Or maybe there should be a websocket connection to get the info about the newest version in real time?
- UX concerns: How should the app behave when a new update is fetched? Should you interrupt the user if they are currently using the mini app and forcefully re-render the whole mini app content? Should you display an alert and ask them if they want to update?

As you can see, the final implementation of such a flow would be totally dependent on the use case/infrastructure/app type etc. I don't see a one size fits all solution here. Our vision for the Repack is to provide universal tools, a means to build upon rather than a specific solution to a specific problem.

That being said: the easiest way to get the updated version of the bundle, without closing and reopening the app, would be to:
- get familiar with the [Super Apps Showcase repository](https://github.com/callstack/super-app-showcase) and speciffically with how the Catalog Server works
- embed the version of the mini app into the URL (used in the container's configuration)
- Figure out a way to get the new container's configuration in the app's runtime whenever a new release of the mini app happens (as mentioned above, by polling, websocket or whatever suits your infrastructure) – this essentially should be built into the Catalog Server
- When you have the URL for the latest version of the mini app you can call `removeResolver` https://re-pack.netlify.app/docs/api/repack/client/classes/ScriptManager#removeresolver method to remove the resolver pointing to the old URL and add a new one.
- Next time when the bundle is requested (i.e. when the user visits a screen with the mini app) the new bundle should be fetched.
