### ISSUE TITLE
node_modules/@callstack/repack/ios/CodeSigningUtils.swift:3:8: Compiling for iOS 12.0, but module 'JWTDecode' has a minimum deployment target of iOS 13.0

### ISSUE THREAD

**Issue by sbefort** [callstack/repack#389]
## Description

I used the `@callstack/repack-init` to add Re.Pack to our project. I was able to install all the pod files. But when building the project in Xcode, I get the error, "
.../node_modules/@callstack/repack/ios/CodeSigningUtils.swift:3:8: Compiling for iOS 12.0, but module 'JWTDecode' has a minimum deployment target of iOS 13.0: ..../Build/Products/Debug-iphonesimulator/JWTDecode/JWTDecode.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

I noticed that in callstack-repack.podspec, line 13 contains the following:
`s.platforms    = { :ios => "12.0" }`

**Comment by hoodedice** [comment]
This is my yarn patch file that resulted in a working ios build:
filename: `@callstack-repack-npm-3.2.0-eae79ff112.patch`

```
diff --git a/callstack-repack.podspec b/callstack-repack.podspec
index db9daa464ee16bd51aa8539aa26ae33620571b71..37d3ea79b8bbe1b2f869dc7363a87d79a3ca1f3c 100644
--- a/callstack-repack.podspec
+++ b/callstack-repack.podspec
@@ -10,7 +10,7 @@ Pod::Spec.new do |s|
   s.license      = package["license"]
   s.authors      = package["author"]
 
-  s.platforms    = { :ios => "12.0" }
+  s.platforms    = { :ios => "13.0" }
   s.source       = { :git => "https://github.com/callstack/repack.git", :tag => "#{s.version}" }
 
   s.source_files = "ios/**/*.{h,m,mm,swift}"
@@ -18,6 +18,6 @@ Pod::Spec.new do |s|
   s.pod_target_xcconfig = { "DEFINES_MODULE" => "YES" }
   
   s.dependency "React-Core"
-  s.dependency 'JWTDecode', '~> 3.0'
+  s.dependency 'JWTDecode', '~> 3.1'
   s.dependency 'SwiftyRSA'
 end
```
repack version: 3.2.0
xcode version: 14.3.1 (14E300c)

**Comment by jbroma** [comment]
Hi @sbefort,

Thank you for reporting the bug, I've confirmed this is in fact incorrect behaviour and created a PR with a fix for this. 

Instead of bumping deployment target to `iOS 13` I've added stricter versioning for pod dependencies as in case of `JWTDecode` the only thing that changed in new minor version was removing support for `iOS 12`. We  still want to support `iOS 12` in according to our policy of supporting last 3 minor versions of `react-native` which still use `iOS 12` as deployment target.
