### ISSUE TITLE
Hot update fail on iOS and Android when mini-app is opened

### ISSUE THREAD

**Issue by ycc759** [callstack/repack#393]
## Environment

react-native 0.71.3 version
Re.Pack 3.2.0 version

## Description

Hot update fail on iOS and Android when mini-app is opened. After "ScriptManager.shared.addResolver", resolver only triggers once when calling the mini-app. I tried to add a log but cannot find the resolver being called when second time calling the mini-app. And it causes cannot trigger "shouldUpdateScript" function to hot update the mini-app. 

I have also tried manually calling "__destroy", "removeAllResolvers", "invalidateScripts", "resolveScript" and "loadScript" but still cannot update mini-app if it is already opened.

May I confirm if it is expected behavior on the resolver or if it is a bug? Please advise, thank you so much.

## Reproducible Demo

https://github.com/callstack/super-app-example/tree/release

**Comment by RafikiTiki** [comment]
I'm not sure I understand the problem you're having. Let's consider this scenario:

You have a Host App and a mini-app which code you're using in the Host App. Both of them have a dev server up and running. In this case, HMR will be available for the Host App code; however, it won't work for the mini-app. This is a know limitation of the Module Federation. To find more context, please see [this comment from the author of the Module Federation plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/394#issuecomment-914928351).

Closing this for now since it's been discussed multiple times in Repack's issues. If this wasn't what you were asking about, feel free to comment/reopen the issue.

**Comment by ycc759** [comment]
@RafikiTiki 
I'm sorry, my description was not clear. 
Let me supplement the scenario.

Host App is in release mode
Mini App JS Bundle hosted by the server

Step 1. Open Host App
Step 2. Open Mini App on Host App
Step 3. Update Mini App JSBundle on server
Step 4. Re-open Mini App on Host App

The Mini App was not updated on step 4, and I tried to add some log and found resolver only trigger on step 2 and not trigger on step 4.

And I have tried to manually call "`__destroy`", "`removeAllResolvers`", "`invalidateScripts`", "`resolveScript`" and "`loadScript`" before step 4 but the Mini App still cannot update.

I think the case is similar to https://github.com/callstack/repack/issues/367 but I have tried to `removeResolver` and `addResolver` again before step 4 but still not working.

**Comment by saravanan6137** [comment]
1. Actually I am not expecting the mini app to be removed without re opening the app instead I need to delete the mini app which is already downloaded manually. Because I see the first time it will download the mini app and next time it will automatically loads (not downloading). But lets say after some time of inactivity I want to manually remove the bundle which is downloaded. So next time when user goes to the same mini app it starts downloading again.
2. Refer the below image. How do we achieve this, will the mini app compare stored cache and new url and if there is a difference then will it download the latest mini app coming from server which has updated version.
<img width="1012" alt="Screenshot 2023-10-19 at 5 07 13 PM" src="https://github.com/callstack/repack/assets/68968235/9784b7b9-6cb4-47f0-bfa5-21267f75555c">
