### ISSUE TITLE
Legacy App Conversion: Generating Metro Bundle for Repack/Webpack Integration

### ISSUE THREAD

**Issue by eduardorfreitas93** [callstack/repack#395]
## Ask your Question

Hey, I have a legacy app with many features, and I'm having trouble converting it to repack/webpack. Is there any way to generate the bundle with Metro and attach it to a repack host?

Example:

Convert the legacy app into a library and install it as an npm dependency in the host project?
Call the Metro bundle of the legacy app in ScriptManager.shared.addResolver?

**Comment by RafikiTiki** [comment]
It's not something I've ever tried, and I'm not exactly sure why you would want to do that without a larger context. Using Repack means complete migration from Metro to Webpack, there's no middle ground here. Otherwise, you'll lose all of the benefits coming with Repack/Webpack/Module Federation.

Having said that, in theory, it should be possible to turn your existing app into a npm package and use it as usual in other apps. That would require adjusting the build/config etc, but it's a npm package configuration thing, out of the scope of Repack.

**Comment by thymikee** [comment]
This seems similar to what MoMo is doing to load 3rd party integrations with their super app: https://developers.momo.vn/v3/docs/app-center/development-guideline/development/create-mini-app/#create-react-native-mini-app. 
Definitely possible, and we don't have ready to use setup for you unfortunately

**Comment by RafikiTiki** [comment]
Closing this one as I feel that the original question was already answered. @eduardorfreitas93 if you feel like you'll need more help from us – please open a new issue with a PoC of what you're trying to achieve and what problems you've faced.
