### ISSUE TITLE
Can't resolve 'react-native-web/dist/exports/StyleSheet/compiler/createReactDOMStyle'

### ISSUE THREAD

**Issue by suwu150** [callstack/repack#442]
Warning in "./node_modules/react-native-reanimated/src/reanimated2/js-reanimated/index.ts": Module not found: Error: Can't resolve 'react-native-web/dist/exports/StyleSheet/compiler/createReactDOMStyle'

Warning in "./node_modules/react-native-reanimated/src/reanimated2/js-reanimated/index.ts": Module not found: Error: Can't resolve 'react-native-web/dist/exports/StyleSheet/preprocess'

When I use react-native-reanimate, I get a warning

**Comment by Stephen-Song** [comment]
same issus to me, any solution?

**Comment by jbroma** [comment]
Hey @suwu150 & @Stephen-Song

from the warnings I can see that you're using `react-native-web`. Re.Pack does not support `web` environment, you should use Webpack without Re.Pack for that -  more on that [here](https://re-pack.netlify.app/docs/web-support).

in case that's not the case - please share a reproduction repository so that we can diagnose this issue, thanks!

**Comment by mayeyun** [comment]
@jbroma 人家想使用react-native在web上运行和你这个完全没有任何关系！

**Comment by oferRounds** [comment]
@jbroma does that mean that if my react-native app uses `react-native-web` as a dependency?

**Comment by oferRounds** [comment]
oh sorry I see now that I made a mistake – I meant `react-native-webview` and not `react-native-web`  🤦‍♂️

**Comment by RafikiTiki** [comment]
@oferRounds You absolutely can use `react-native-webview` package with Repack :)

**Comment by oferRounds** [comment]
Sounds good! I still have this issue though, but hopefully I’ll be able to over come it soon
https://github.com/callstack/repack/issues/467
