### ISSUE TITLE
Do containers that are not deployed independently need to set eager to true for react and react-native dependencies?

### ISSUE THREAD

**Issue by JoonDong2** [callstack/repack#462]
In the following document, it is mentioned to set eager of react and react-native dependencies to true.
[https://re-pack.netlify.app/docs/module-federation/#react-and-react-native-must-be-eager-and-singleton](https://re-pack.netlify.app/docs/module-federation/#react-and-react-native-must-be-eager-and-singleton)

However, I think that if the host app shares react and react-native dependencies, the container app can retrieve the shared dependencies through the `__webpack_require__.f.consumes` function.

Is it really necessary to set the container's `eager` to true as described in the documentation?
Because of `eager: true`, the bundle file size becomes too large.

**Comment by jbroma** [comment]
Hey @JoonDong2,

as far as I know, for proper initialization, setting `react` and `react-native` is required. I have not experimented in that area because it was a never a big issue to begin with. I'm unable to provide you with a more advanced take on the subject.

You're saying that bundle file size becomes too large, how large are we talking about here?. For our TesterApp, which isn't optimized at all for the main chunk filesize, it takes roughly 1,5 MB of diskspace.

**Comment by JoonDong2** [comment]
> Hey @JoonDong2,
> 
> as far as I know, for proper initialization, setting `react` and `react-native` is required. I have not experimented in that area because it was a never a big issue to begin with. I'm unable to provide you with a more advanced take on the subject.
> 
> You're saying that bundle file size becomes too large, how large are we talking about here?. For our TesterApp, which isn't optimized at all for the main chunk filesize, it takes roughly 1,5 MB of diskspace.

Setting eager:true reduces the size in kb because react and react-native JavaScript code is excluded from the app.container.bundle file.
I think this is a significant difference.
