### ISSUE TITLE
Unable to load script. Make sure you're either running Metro

### ISSUE THREAD

**Issue by Juan2662** [callstack/repack#484]
## Environment

Monorepo
react-native: 0.72.5
webpack: 5.89.0
@callstack/repack: 3.6.0

## Description

I followed all steps here -> https://re-pack.netlify.app/docs/getting-started (using @callstack/repack-init)
When I try to run my android application I get this error
![image](https://github.com/callstack/repack/assets/58581443/daa7ecdd-9ab4-403f-a293-9c53282eeee2)

and I see this output in my terminal
![image](https://github.com/callstack/repack/assets/58581443/612cf1af-c53e-4f24-b1c2-fd365ca2dee1)

Works fine for iOS, but for Android I'm getting this bug

## Reproducible Demo

Create a new react native proyect and follow all steps here  https://re-pack.netlify.app/docs/getting-started

**Comment by jbroma** [comment]
Hi @Juan2662,

if it works fine on iOS and the problem is happening only on Android, I'm 99% sure it's because of Re.Pack server listening on IPv6 interface only. You can fix that by running the `webpack-start` command with additional option: `--host 127.0.0.1`. 

This should resolve your issue on Android for now, we plan to fix it in 4.0.0

**Comment by Juan2662** [comment]
Hi @jbroma Yes, that fix my issue, thank you!
When can we have 4.0.0 live ?

**Comment by jbroma** [comment]
Soon 😁
