### ISSUE TITLE
JWTDecode version conflicts with other package

### ISSUE THREAD

**Issue by allen012694** [callstack/repack#531]
Hi, is there any plan for us to update JWTDecode version to 3.1.0 in repack's podspec?
I am having problem when using this together with react-native-auth0 >= 3.0.0
Many thanks.

https://github.com/callstack/repack/blob/b0b8613eab82641e91607e0931eafc2360ff42a2/packages/repack/callstack-repack.podspec#L21C18-L21C39

```
[!] CocoaPods could not find compatible versions for pod "JWTDecode":
  In Podfile:
    A0Auth0 (from `../node_modules/react-native-auth0`) was resolved to 3.0.2, which depends on
      Auth0 (= 2.5.0) was resolved to 2.5.0, which depends on
        JWTDecode (~> 3.1)

    A0Auth0 (from `../node_modules/react-native-auth0`) was resolved to 3.0.2, which depends on
      JWTDecode (= 3.1.0)

    callstack-repack (from `../node_modules/@callstack/repack`) was resolved to 3.7.0, which depends on
      JWTDecode (~> 3.0.0)
```

**Comment by jbroma** [comment]
Hi @allen012694,

as of right now, we can't bump the `JWTDecode` to `3.1.0` because it doesn't support iOS 12, which is a minimal deployment target for RN `0.72` & `0.71` which are still supported by `Re.Pack`. 

Re.Pack states to support current + 2 last previous versions of RN. In `0.73` the minimal deployment target was changed to `13.4` so when RN `0.75` drops, we will be happy to update the `JWTDecode` library to the newest version. 

To resolve your issue, I suggest using `patch-package` or something similar to modify the podspec for `Re.Pack` locally. I'm not a CocoaPods expert but I'm not sure there is any other way to resolve this at this moment.
