### ISSUE TITLE
build .apk file ???

### ISSUE THREAD

**Issue by HongQuang231** [callstack/repack#549]
## Ask your Question

when i build apk file by android studio, it's successfully, but when I try install apk file into real device, app throw error look like this 
<img width="347" alt="image" src="https://github.com/callstack/repack/assets/92237330/2773afe8-5d21-4343-8c4b-1428fe4d0fd0">
help me fix this????

**Comment by jbroma** [comment]
@HongQuang231 this is most likely due to dev-server listening only to IPv6 by default, try running `react-native start --host 127.0.0.1` to fix this. 

This is also something we fixed in 4.0.0. You can try upgrading to `@callstack/repack` to version `4.0.0-rc.0` and see if that fixes the issue by itself

**Comment by mlakmal** [comment]
noticed same issue. and i was able to use --host flag to point to 127.0.0.1 and it worked fine...

**Comment by jbroma** [comment]
I'm closing this one since the solution was provided and Re.Pack `4.0.0` is already released as stable and it includes the fix for this scenario. If you issue is still there please open a new issue.
