### ISSUE TITLE
Bug in `invalidateScripts` leading to app crash

### ISSUE THREAD

**Issue by sriharshaarangi** [callstack/repack#553]
## Environment

React Native android (but I believe the bug is not specific to RN android)

## Description

Calling `invalidateScripts` for a chunk is causing a crash when next attempting to use that chunk. On debugging it, the chunk file is getting deleted, but the entry in sqlite db is not getting cleared. It looks like there is a [bug in `invalidateScripts` method](https://github.com/callstack/repack/blob/main/packages/repack/src/modules/ScriptManager/ScriptManager.ts#L414 ). `resolveScripts` method appends caller to the `scriptId` to get the cacheKey (```const cacheKey = `${scriptId}_${caller ?? 'unknown'}`;```), while `invalidateScripts` directly uses `scriptId` as the cacheKey. 

## Reproducible Demo

1. Have a remote code split chunk.
2. Call `invalidateScripts` with that chunk's scriptId
3. Try using that chunk in UI, it leads to crash. `com.facebook.react.common.JavascriptException: ChunkLoadError: Loading chunk <scriptId> failed`

**Comment by jbroma** [comment]
> @jbroma I am having few queries before getting into the fix:
> 
> 1. [`caller` Documentation says](https://re-pack.netlify.app/docs/api/repack/client/classes/ScriptManager#resolvescript) `Name of the calling script - it can be for example: name of the bundle, chunk or container.` However, the default value is `main` which is not the default bundle/chunk/container name.
> 2. Should default caller value be made `main` instead of `unknown`?
> 3. I am unable to grasp what value the caller is adding for cacheKey in the first place, if the underlying downloaded file  is the same irrespective of the caller value (I am assuming so as per the downloaded chunk file name). Can you please help elaborate, or point me to any other documentation behind the design decision?

1. & 2. The name `main` comes from webpack, when you declare entry with a string or an array, it defaults the entry chunk name to `main`. See [webpack docs](https://webpack.js.org/configuration/entry-context/#naming). So it's a decent default I think, but it's good to double check this if this is really the case.
3. I've looked at it and I'm pretty sure the name is there to create some sort of uniqueID, since `scriptID` is a string and can easily be duplicated in an app. Adding a caller creates a scope for it so it's harder to get a collision.

**Comment by jbroma** [comment]
I suppose we could drop the caller altogether for the uniqueID, and rely on users specyfing [`output.uniqueName`](https://webpack.js.org/configuration/output/#outputuniquename) to avoid collisions.
