### ISSUE TITLE
URL.search is not implemented

### ISSUE THREAD

**Issue by jaysson** [callstack/repack#57]
## Environment
- Yarn workspaces
- Typescript
- Android
- https://github.com/charpeni/react-native-url-polyfill

## Description

When I try to use `new URL.search`, it throws `Error: not implemented`. It works fine without repack.

## Reproducible Demo
Just put this in `index.js`

```js
const url = new URL('https://example.com');
console.log(url.search);
```

**Comment by zamotany** [comment]
This is the implementation for URL: https://github.com/facebook/react-native/blob/0.64-stable/Libraries/Blob/URL.js#L195 which is used by Metro and Re.Pack. I've checked both with Metro and Re.Pack and with both the `not implemented` error is thrown.
I'm curious how it was working before without Re.Pack. Do you have some polyfill for it?

**Comment by jaysson** [comment]
Sorry for not mentioning it in before. Using https://github.com/charpeni/react-native-url-polyfill

**Comment by zamotany** [comment]
`whatwg-url` related dependencies have to be transpiled by Babel in order to work. Metro transpiles everything by default, that's why it was working.

Add `/node_modules(.*[/\\])+whatwg-url/` to `include` array for 1st `babel-loader`: https://github.com/callstack/repack/blob/main/templates/webpack.config.js#L148

Then you will be able to use `import 'react-native-url-polyfill/auto'` or to the `entry` array in `webpack.config.js`:
```js
entry: [
    ...ReactNative.getInitializationEntries(reactNativePath, {
      hmr: devServer.hmr,
    }),
    'react-native-url-polyfill/auto',
    entry,
  ],
```

**Comment by jaysson** [comment]
That worked. Thank you so much.
