### ISSUE TITLE
Vendored Device class is broken when it comes to debugging

### ISSUE THREAD

**Issue by yard** [callstack/repack#578]
## Environment
Nothing specific, an empty react-native project with installed repack (I have used 3.7.0, but other versions might be affected too).

## Description
Vendored version of `metro-inspector-proxy/src/Device.js` is flawed: it does not handle `Debugger.getScriptSource` properly when the script URL is an actual URL, not a file path. Since it is the case for every development build (the script source is actually the URL to a bundler endpoint), Chrome DevTools would display an error message instead of the script source, making debugging impossible.

Conveniently enough, react-native developers have accounted for that in their [implementation](https://github.com/facebook/react-native/blob/main/packages/dev-middleware/src/inspector-proxy/Device.js#L648) – I have tried replacing the `Device` class with the one taken from `@react-native/dev-middleware` package and it seems to be working flawlessly.

I am curious if there is any reason for using the vendored version? 

## Reproducible Demo
Try debugging any project with Chrome DevTools.

**Comment by jbroma** [comment]
hi @yard, thanks for reporting that! 

We're currently working on supporting the new experimental debugger in #508, not sure what's going to happen with legacy remote debugging since it's already deprecated in RN, so we might just leave Flipper + experimental debugger. 

@RafikiTiki what's your take on this?

**Comment by yard** [comment]
hi @jbroma, happy to help and thank you for amazing work on the library!
Please do let me know if I can help in any way.

**Comment by RafikiTiki** [comment]
Hey @yard – as @jbroma mentioned we're currently migrating to the new package exposed by the RN corre team – `@react-native/dev-middleware`. Enabling the experimental debugger was the main reason for this change, but I'm glad it'll sort out your issue as well.

Since Remote Debugging will be removed by the RN core team, we won't be supporting this. We'll definitely treat the experimental debugger as the main focus. As for the Flipper, since it would have to be manually configured from the next version (https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#flipper--react-native-integration) – it might need some additional configuration work that I'm not sure if should be done on the Repack or the consumer side – we'll see how this will play out once the experimental debugger changes are released in v4.
