### ISSUE TITLE
Task :app:createBundleReleaseJsAndAssets_SentryUpload_*************************** FAILED

### ISSUE THREAD

**Issue by akshay-capgemini** [callstack/repack#668]
Im using sentry in my repack rect native application. The sentry is working fine in debug APK and Im also able to generate the debug APK. But when I try to generate the release APK. The build failed with the below issue.

> Task :app:createBundleReleaseJsAndAssets_SentryUpload_com.********************** FAILED
Copy `debugId` from packager source map to Hermes source map...
Packager source map does not have `debugId`.
Check generated source map for Debug ID: /Users/**************************/host/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map does not contain 'debugId' nor 'debug_id'.

**Comment by jbroma** [comment]
Hi @akshay-capgemini,

In metro `debugIds` are [added through a custom serializer](https://docs.sentry.io/platforms/react-native/manual-setup/metro/#configuration) - since the bundler architecture is different there is no way to reuse that. AFAIK there's no integration from Sentry for Re.Pack so you would have to reverse engineer the stuff the serializer does and make a webpack plugin out of it.

**Comment by jbroma** [comment]
Closing since this isn't currently on the roadmap

**Comment by skinsapp** [comment]
Is there another solution/service recommended instead of Sentry?

**Comment by jbaldaraje-cg** [comment]
@jbroma  any update on this?

**Comment by gronxb** [comment]
Try this https://github.com/gronxb/repack-plugin-sentry
